version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container2
    environment:
      MYSQL_DATABASE: databasesanszz 
      MYSQL_USER: admin
      MYSQL_PASSWORD: 16161616
    ports:
      - "3306:3306"
    networks:
      - ola_network


  springboot:
    build: .
    container_name: sanszz_saleshistory_app
    ports:
      - "8978:8978"
    depends_on:
      - mysql
    networks:
      - ola_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-sanszz.cj9rshqboeoo.us-west-1.rds.amazonaws.com:3306/databasesanszz
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 16161616

networks:
  ola_network:
    driver: bridge
